name: "name-of-this-experiment-run"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "output"
seed: 0
 
data_type: "random-camera-datamodule"
data:
  batch_size: 8
  # batch_size: 4
  # batch_size: 2
  # batch_size: 1
  eval_camera_distance: 2.0
  camera_distance_range: [1.5, 2.0]
  # camera_distance_range: [2.0, 2.5]
  # camera_distance_range: [2.5, 3.0]
  light_sample_strategy: "dreamfusion3dgs"
  height: 1024
  width: 1024
  # resolution_milestones: [600]
  eval_height: 1024
  eval_width: 1024
  elevation_range: [-30, 30]

  enable_near_head_poses: false
  head_offset: 0.65
  head_camera_distance_range: [0.4, 0.6]
  head_prob: 0.25
  head_start_step: 1200
  head_end_step: 3600
  head_azimuth_range: [0, 180]

  # enable_near_back_poses: true
  enable_near_back_poses: false
  back_offset: 0.65
  back_camera_distance_range: [0.6, 0.8]
  back_prob: 0.20
  back_start_step: 1200
  back_end_step: 30000
  back_azimuth_range: [-180, 0]

  enable_near_pant_poses: true
  pant_offset: -0.15
  pant_camera_distance_range: [0.6, 0.8]
  pant_prob: 0.10
  pant_start_step: 0
  pant_end_step: 30000
  pant_azimuth_range: [-180, 180]

  opacity_reset_list: [5000]
  opacity_reset_val: 0.01
  prune_min_opacity: 0.01
  # prune_min_opacity: 0.005
  inner_init_sample_num:  300000
  # [start_iter, sds_bs, w_sds_bs_body_loss]
  sds_cfg_list: [1, 8, 0.00001]
  apose_prob: 0.5
  end_densify_iter: 12000
  apply_op_control_start_iteration: 300
  apply_op_control_end_iteration: 30000

  lambda_normal_iter: 3000
  lambda_normal: 0.05
  lambda_dist_iter: 2000
  lambda_dist: 1000.0
  apply_sam_seg: false
  apply_evaluate: true
  apply_foreground_mask: false # Set true for customized monocular video

  gender: "female"
  text: "a photo of a woman wearing a shirt"
  negative_text: ""
  # Don't use any other negative text there.
  # Evidence 
  #   - output/4d-dress-00175_Inner_1-Inner-Take4-f00110/results/0502_1234_multilayer_2dgs_outer/multilayer-inpaint-upper-refine-male.yaml
  #   - output/4d-dress-00175_Inner_1-Inner-Take4-f00110/results/0502_1606_multilayer_2dgs_outer/multilayer-inpaint-upper-refine-male.yaml
  #   - output/4d-dress-00175_Inner_1-Inner-Take4-f00110/results/0502_2244_singlelayer_2dgs/singlelayer-male.yaml
  #   - output/4d-dress-00175_Inner_1-Inner-Take4-f00110/results/0503_0112_singlelayer_2dgs/singlelayer-male.yaml
  # negative_text: "close up, cropped, worst quality, low quality, jpeg artifacts, duplicate, morbid, mutilated, mutation, deformed, blurry, bad anatomy, bad proportions, muscular"
  text_obj: ""
  negative_text_obj: ""
  add_directional_text: true

  w_img_loss: 3.0
  w_dist_loss: 3.0
  w_normal_loss: 3.0

system_type: "gaussiandreamer-system"
system:
  radius: ${data.eval_camera_distance}
  # texture_structure_joint: true
  controlnet: true
  smplx_path: "data/models"
  disable_hand_densification: false
  pts_num: 100000
  densify_prune_start_step: 300
  densify_prune_end_step: 2100
  densify_prune_interval: 300
  size_threshold: 20
  max_grad: 0.0002
  # max_grad: 0.000002
  gender: 'neutral'
  prune_only_start_step: 2400
  prune_only_end_step: 3300
  prune_only_interval: 300
  prune_size_threshold: 0.008
  apose: true
  bg_white: false

  prompt_processor_type: "texture-structure-prompt-processor"
  prompt_processor:
    use_perp_neg: false
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-base"
    negative_prompt: "shadow, dark face, colorful hands, eyeglass, glasses, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"
    prompt: ???

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_sparsity: 1.
    lambda_opaque: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 3600
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: false # save at each validation time
  save_top_k: -1
  # every_n_train_steps: ${trainer.max_steps}
  every_n_train_steps: 50000